# Generated by Django 2.1.7 on 2019-03-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learning_Objectives',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('objective', models.CharField(max_length=300)),
            ],
        ),
    ]
