# Generated by Django 2.1.7 on 2019-03-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learning_Objectives',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('objective', models.CharField(max_length=100)),
                ('principle', models.IntegerField(default=1)),
                ('grade', models.IntegerField(default=1)),
                ('evidence', models.CharField(max_length=150)),
                ('wid', models.IntegerField(default=1)),
            ],
        ),
    ]
