# Generated by Django 2.1.7 on 2019-03-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning_objectives',
            name='grade',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='learning_objectives',
            name='principle',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='learning_objectives',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
